# docker compose  -f docker-compose-trt-gpt.yml up
services:
 trtllm-server:
    image: nvcr.io/nvidia/tensorrt-llm/release:1.3.0rc10
    container_name: trtllm_llm_server
    command:
      - bash
      - -c
      - |
        set -ex
        export TIKTOKEN_ENCODINGS_BASE="/tmp/harmony-reqs"
        mkdir -p $$TIKTOKEN_ENCODINGS_BASE
        wget -P $$TIKTOKEN_ENCODINGS_BASE https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken
        wget -P $$TIKTOKEN_ENCODINGS_BASE https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken

        echo "Downloading model: $$MODEL_HANDLE"
        hf download $$MODEL_HANDLE

        echo "Creating config file..."
        cat > /tmp/extra-llm-api-config.yml <<'EOFCONFIG'
        print_iter_log: false
        kv_cache_config:
          dtype: "auto"
          free_gpu_memory_fraction: 0.9
        cuda_graph_config:
          enable_padding: true
        disable_overlap_scheduler: true
        EOFCONFIG

        echo "Config file contents:"
        cat /tmp/extra-llm-api-config.yml

        echo "Starting trtllm-serve with model: $$MODEL_HANDLE"
        exec trtllm-serve "$$MODEL_HANDLE" \
          --max_batch_size 64 \
          --trust_remote_code \
          --host 0.0.0.0 \
          --port 8355 \
          --extra_llm_api_options /tmp/extra-llm-api-config.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - HF_TOKEN=${HUGGINGFACE_HUB_TOKEN}
      #- MODEL_HANDLE=openai/gpt-oss-20b
      - MODEL_HANDLE=nvidia/gpt-oss-puzzle-88B
    volumes:
      - ${HOME}/.cache/huggingface/:/root/.cache/huggingface/
    ports:
      - "8355:8355"
    restart: unless-stopped
